### ISSUE TITLE
Add `-tai` form as an option to the -te/present/past list

### ISSUE THREAD

**Issue by loldebyte** [baileysnyder/japanese-conjugation#16] opened 2023-09-12 11:54 UTC
First of all, thanks a bunch for the great tool, it's helped me tons already and I'm here because I hope I can help making it help even more. And that's a lot of `help`s but that'll have to do, lunch break is over :D

It is my understanding that the `-tai` form acts for (almost ?) all intents and purposes as a conjugation much like the supported ones, therefore I propose to add it to the supported conjugations.

From what I know and understand it seems to be that it should be _relatively_ easy to implement, but as I'm far from being an accomplished JS developper I figured I might as well open anissue and check with you before jumping head first into a wall and giving up.

Am I correct when I say such a change would require the following changes to `main.js` :
- updating all `xxConjugation` methods with a complete `else if (tense == "tai")` clause ;
- add a matching case to `conjugationFunctions` ;
- add _something_ in the past/present affirmative/negative loop [here](https://github.com/baileysnyder/japanese-conjugation/blob/83d22499cc71de491edfbc10bfa8bb80749f328f/src/main.js#L634C2-L634C2) for the additional conjugations to be added to the array

The following change to `optionfunctions.js` :
- a `verbtai` clause in `verbs` to the `optionRemoveFunctions` constant that returns `isNotTense(x, "tai-form")` 

And inserting a similar line below line 87 in `index.html` : `<tr><td><input id="verbtai-checkbox" type="checkbox" name="verbtai"><label for="verbtai-checkbox">-tai form</label></td></tr>`

In addition to matching changes I frankly have no idea about as of yet to `style.css` ?

**Comment by baileysnyder** [comment] 2023-09-12 22:11
Thank you for the suggestion, and sorry you had to dig through my old wonky code to come up with all of these details lol. Unfortunately, I think this is going to be a much bigger change than what you pointed out, because -tai conjugations can also be present or past tense. I've been able to group past, present, and -te altogether in the UI and the conjugationFunctions because -te doesn't have a notion of present or past tense, but this will break if we try adding -tai or really any other conjugation type. Then there has to be support for a conjugation prompt with 4 tokens like "たい past affirmative plain" instead of the current max which is 3 like "past affirmative plain".

Coding difficulty aside, I'm also not sure that -tai is worth adding as a conjugation option. I haven't studied Japanese in awhile, but if I recall you basically take the stem of the verb, which is the same used during polite affirmative ます conjugations, then tack on たい. Then たい is conjugated like an い adjective, which is also already in the app. From one perspective, beginners may either not realize these similarities, or realize them but still want to practice to really solidify things. But from another perspective, it is a lot of work to implement, I expect it will not provide much value to the average user once they realize the similarities to the other conjugations, and I might be a little crazy for this one but I don't like adding extra settings if I can avoid it. Opening the settings and seeing a lot of options can make it more daunting to first of all understand what all the options are, but also if you have the goal of going through all the conjugation types can make the goal seem that much further away.

In my view, the "complete" version of this app would probably look like this in the options section:
_________
te
volitional
potential
passive
causitive
_________
present
past
_________

The problem is it will take some work to separate the present and past conjugations out like that, and I'd need to re-study Japanese for a bit to feel confident in the conjugations I code up 😭

**Comment by baileysnyder** [comment] 2023-09-13 23:17
No bother at all.

> I find I remember the meanings of tenses present on your app much better (simply by getting more accustomed to them I assume), not so much for the conjugation part itself

I hadn't considered this before but it makes sense. I could imagine this being an even bigger thing if I start adding the weird ones like volitional, potential, etc. where I personally don't even know what the equivalent English conjugations should be lol.

I'll go ahead and close the issue, but this helped me organize my thoughts on the app in general so thanks for all the input 👍

**Closed by baileysnyder** 2023-09-13 23:17 UTC
